name: Deploy Backend to VPS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            APP_DIR="$HOME/apps/CapstoneBE"

            # Pull latest changes
            cd $APP_DIR
            git pull origin ${{ github.ref_name }}

            # Install dependencies
            cd backend
            npm install --production

            # Restart PM2 process
            pm2 restart capstone-backend --update-env || pm2 start server.js --name capstone-backend --time
            pm2 save

            # Show status
            pm2 list

            echo "Backend deployment completed at $(date)"

      - name: Health check
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sleep 5
            if pm2 show capstone-backend | grep -q "online"; then
              echo "Backend is running successfully"
            else
              echo "Backend failed to start"
              pm2 logs capstone-backend --lines 50
              exit 1
            fi

      - name: Deployment notification
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Backend deployment successful!"
          else
            echo "Backend deployment failed!"
            exit 1
          fi



